name: Deploy Web by Poomrapee-020 

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code by Poomrapee-020 
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
